process.env.BINANCE_API_KEY = 'BINANCE_API_KEY';
process.env.BINANCE_SECRET_KEY = 'BINANCE_SECRET_KEY';
process.env.AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';
process.env.AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';
